services:

  tests:
    container_name: utopia-pools-tests
    build:
      context: .
      args:
        DEBUG: true
    networks:
      - pools
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./dev:/usr/src/code/dev
      - ./phpunit.xml:/usr/src/code/phpunit.xml
      - ./dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

networks:
  pools:
